### ISSUE TITLE
Fails to precompile on the latest master (https://github.com/JuliaLang/julia/commit/c0d06d3219751d28237cb32d9d6f7e2ef45916cd)

### ISSUE THREAD

**Issue by aviatesk** [JuliaLang/MbedTLS.jl#226]
with the following error:
```julia
ERROR: LoadError: LoadError: UndefVarError: libmbedtls not defined
Stacktrace:
  [1] MbedTLS.SSLConfig()
    @ MbedTLS ~/.julia/packages/MbedTLS/VbsaQ/src/ssl.jl:18
  [2] top-level scope
    @ ~/.julia/packages/HTTP/IAI92/src/ConnectionPool.jl:661
  [3] include(mod::Module, _path::String)
    @ Base ./Base.jl:379
  [4] include(x::String)
    @ HTTP ~/.julia/packages/HTTP/IAI92/src/HTTP.jl:1
  [5] top-level scope
    @ ~/.julia/packages/HTTP/IAI92/src/HTTP.jl:25
  [6] include
    @ ./Base.jl:379 [inlined]
  [7] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::Nothing)
    @ Base ./loading.jl:1144
  [8] top-level scope
    @ none:1
  [9] eval
    @ ./boot.jl:360 [inlined]
 [10] eval(x::Expr)
    @ Base.MainInclude ./client.jl:446
 [11] top-level scope
    @ none:1
```

I found we can precompile this package if we checkout to before [`f45c799`](https://github.com/JuliaLang/julia/commit/f45c799985d24ee79e051bceac1884e6868d0c93), and I feel some changes between [`54946b0`](https://github.com/JuliaLang/julia/commit/54946b01bd04b24f72c862190e8d2eab7845ec68) and [`e378767`](https://github.com/JuliaLang/julia/commit/e37876793f77b516c30000b66b373e71b1e462e5) are culprit

/cc @staticfloat @giordano maybe you guys know what's going on ?

**Comment by staticfloat** [comment]
Yeah, it's a known issue with a change in platform parsing.  We're going to be starting to fix the ecosystem over the next few days; the change in parsing strategy is necessary and slight, but some JLL wrappers have assumptions baked into them about how the triplet parsing roundtrips that has been broken.

**Comment by giordano** [comment]
If that's macOS it's a known issue, don't worry about it, it'll be fixed in a few days

**Comment by aviatesk** [comment]
ah yeah I'm on macOS

> We're going to be starting to fix the ecosystem over the next few days
> it'll be fixed in a few days.

nice, looking forward to that. I would like to keep this open for those who encounter the same issue, but make sure to close this once it gets resolved.

**Comment by aviatesk** [comment]
this particular error seems to be fixed on the latest master, thank @staticfloat and @giordano !
