### ISSUE TITLE
MbedTLS 1.1.1 causing issues for authentication on Azure

### ISSUE THREAD

**Issue by samtkaplan** [JuliaLang/MbedTLS.jl#250]
Hi,

I'm noticing that MbedTLS 1.1.1 is causing issues when authenticating on Azure using the [AzSessions.jl](https://github.com/ChevronETC/AzSessions.jl) package.  In particular, I am noticing that the AzSessions.jl retry logic is being hit more than expected with a `Base.IOError` thrown.  The trace indicates that the problem may be coming from the MbedTLS `ssl_write` method.  I suppose that this may be related to #247?

Here is a simple code to test (Please note that `sessions` is using [device code flow for authentication](https://chevronetc.github.io/AzSessions.jl/stable/reference/#Reference)):
```julia
using AzSessions, Dates
session = AzSession(protocal=AzDeviceCodeCredentials, client_id="myclientid", tenant="mytenant")
while true
    sleep(120)
    tkn = token(session)
    @info "tkn=$(tkn[1:5]), $(now())"
end
```
The error is triggered when AzSessions uses its OAuth2 refresh-token to retrieve a new OAuth2 access-token.  Note that the refresh-token logic is only triggered about once per hour (when the access-token expires).  Below is a screen-shot where on the left we are using MbedTLS 1.1.1, and on the right we are using MbedTLS 1.1.0.
![image](https://user-images.githubusercontent.com/4575854/181924771-6a0aa51b-f818-4a0b-b917-b9f8c0dcfa5f.png)
Notice that on the right, we hit the `IOError` causing the AzSessions retry logic to be invoked, where-as on the right (with MbedTLS 1.1.0) we don't hit the retry logic.

I have not done much to dig into the possible root cause, but I thought I would share my current observation.

Thanks!

Sam

**Comment by quinnj** [comment]
I just tagged v1.1.2 (like 5 minutes ago) with a fix for a an issue introduced in v1.1.1. Could you pull and try again to see if the issue persists?

**Comment by samtkaplan** [comment]
Unfortunetly, it looks like the problem might still be there with MbedTLS 1.1.2.

Here's the Pkg.status()
![image](https://user-images.githubusercontent.com/4575854/181936542-60d0c1b9-ecc1-455e-9bb1-008172a99509.png)
and here's the output (same test-code as before):
![image](https://user-images.githubusercontent.com/4575854/181936563-7f6509d1-d10b-45b0-ae15-1f9baef4f4eb.png)
Note that the error message is a little less verbose this time, but I can add back the printing of the trace and run again.

**Comment by quinnj** [comment]
ok, pinging @vtjnash here; I'm currently on vacation, but can help dig in and try to figure out what's going on once I get back (next week).

**Comment by samtkaplan** [comment]
Not a big rush since using `1.1.0` is a simple fix for now.

**Comment by samtkaplan** [comment]
Hi,

Just a small update given the release of MbedTLS 1.1.3 (Thanks to @mbauman for pointing me to the new release).   It looks like we have the same issue.  On the left is mbedtls 1.1.0 where we see no errors thrrown, in the middle is with mbedtls 1.1.3 where we see the same IOError, and on the right is mbedtls 1.1.2.
![image](https://user-images.githubusercontent.com/4575854/183261673-5fd00c0e-7f48-42de-b1aa-bfd0491dced6.png)
Note that in  the case of mbedtls 1.1.3, I also see an mbedtls error which I guess was added between mbedtls 1.1.2 and 1.1.3 releases (see below screen-shot).
![image](https://user-images.githubusercontent.com/4575854/183261753-4f95705e-e437-42a6-ab2a-14e095ec64a7.png)

Apologies for the lack of a trace in these error messages.  I can try another run with mbedtls 1.1.3 and where I collect the traces.

**Comment by vtjnash** [comment]
Do you have local changes to AzSessions? I tried your example above with my own account, and just got back generic "invalid_client" messages due to the lack of a client_secret, so it seemed that this would not be able to get a token with that authentication flow.

**Comment by samtkaplan** [comment]
@vtjnash  I do not have any local changes to AzSessions other than changing the `Project.toml` file to allow for a newer version of MbedTLS.  With respect to the error that you are seeing, I'm not sure.  The page [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-device-code) does not seem to indicate that the `client_secret` is needed.  Perhaps there is some setting in the Azure application that needs to be changed.  I can look into it, and see if I can find an answer.

**Comment by vtjnash** [comment]
Okay, I found there is a checkbox for this (https://stackoverflow.com/questions/45609432/how-do-i-resolve-the-error-aadsts7000218-the-request-body-must-contain-the-foll)

It looks like this is an unhandled race condition in HTTP.jl with the ConnectionPool, but we can also reduce the duration of the race window so that it is harder to hit that bug, which helps to make this unlikely: https://github.com/JuliaWeb/HTTP.jl/pull/901

**Comment by quinnj** [comment]
@samtkaplan, can you confirm that upgrading HTTP.jl (v1.2.1) fixes the issue here? I realize this got auto-closed, but just wanted to follow up with you.

**Comment by samtkaplan** [comment]
@quinnj Thanks so much for checking in.  I really appreciate all of the work.  Unfortunately, it looks like there is still an issue.  Perhaps, Interesting, the issue seems to be slightly different now in that it manifests more quickly than it did before.
![image](https://user-images.githubusercontent.com/4575854/184431072-e60cae1b-e84f-4a57-8577-408fe3ccc762.png)

**Comment by quinnj** [comment]
Hmmm, yeah, so this error should be benign; i.e. your requests should keep working. This is more reporting that a connection we were thinking of reusing ended up getting closed.

@vtjnash, what do you think of changing `montior_idle_connections` in HTTP.ConnectionPools to:
```julia
function monitor_idle_connection(c::Connection)
    try
        if eof(c.io)                                  ;@debugv 3 "💀  Closed:     $c"
            close(c.io)
        end
    catch ex
        @try Base.IOError close(c.io)
        ex isa Base.IOError || rethrow()
    end
    nothing
end
```

**Comment by vtjnash** [comment]
That sounds good.

Additionally, another reliability feature I think is missing here is checking whether it is still in the right state before calling eof or close. If the object already is being reused or closed, it should not do anything here. A simple age counter that increments on every use, and passed as an argument here, would help do that. (And would allow implementing it more accurately to the comment, which says it would close if any data gets received)

**Comment by samtkaplan** [comment]
Hi,

I just wanted to give a small update from my side.  With MbedTLS 1.1.3 and HTTP master, things are working great.  I guess we can close this.  Do you know when the next version of HTTP.jl will be released?  I'm guessing that this [commit ](https://github.com/JuliaWeb/HTTP.jl/commit/4d59f76fc7d74581a5cd7802bbdee2bd9ae69b09) that is not yet in a release was the final one required to close this issue (although as you noted that particular "error" message should be benign) .  No rush, just curious.

Many thanks!!

**Comment by quinnj** [comment]
Just made a new HTTP.jl 1.3.0 release today that includes the commit. Thanks for the help tracking these issues down!
