### ISSUE TITLE
Cannot find cert.pem in compiled applications

### ISSUE THREAD

**Issue by vitornesello** [JuliaLang/MbedTLS.jl#251]
Hello,

[MbedTLS.jl](https://github.com/JuliaLang/MbedTLS.jl) is used as a dependency in one of my applications.
We deploy a compiled version of this app using [PackageCompiler.jl](https://github.com/JuliaLang/PackageCompiler.jl) and everything was working just fine until one of the latest releases of the month of July.

What happens is that [this function](https://github.com/JuliaLang/MbedTLS.jl/blob/bc8083b9062894da7b4e88320fe69866c8ebd1b1/src/ssl.jl#L793-L805) (code copied below) is trying to access the file `cert.pem` using the variable `Sys.BINDIR` as reference path. The problem is that in the compiled app the certificate does not exist in the expected directory.

How could I fix it? I am keen to opening a PR if the problem really comes from this package

```julia
function __sslinit__()
    c_send[] = @cfunction(f_send, Cint, (Ptr{Cvoid}, Ptr{UInt8}, Csize_t))
    c_recv[] = @cfunction(f_recv, Cint, (Ptr{Cvoid}, Ptr{UInt8}, Csize_t))
    c_dbg[] = @cfunction(f_dbg, Cvoid, (Any, Cint, Ptr{UInt8}, Cint, Ptr{UInt8}))
    # Note: `MozillaCACerts_jll.cacert` is filled by `__init__`
    fallback = abspath(joinpath(Sys.BINDIR, "..", "share", "julia", "cert.pem"))
    if isfile(MozillaCACerts_jll.cacert)
        DEFAULT_CERT[] = read(MozillaCACerts_jll.cacert, String)
    else
        DEFAULT_CERT[] = read(fallback, String)
    end
    return
end
```

**Comment by KwatMDPhD** [comment]
Hi, I have the exact same issue her ehttps://github.com/KwatMDPhD/GSEA.jl/issues/59. I hope you could help take care of this.

**Comment by KwatMDPhD** [comment]
And this is the same issue https://github.com/JuliaLang/MbedTLS.jl/issues/242

**Comment by KwatMDPhD** [comment]
This is fixed.

**Comment by vitornesello** [comment]
Thanks, guys
